project:
  type: default

format:
  pdf:
    fig-pos: "H"
    number-sections: false
    documentclass: scrreprt  # Allows more flexible margin control
    include-in-header:
      text: |
        \usepackage[a4paper,margin=1in]{geometry}
        \newcommand{\blank}{\underline{\phantom{00000}}}
        \newcommand{\blanker}[1]{\underline{\makebox[#1]{}}}
        \usepackage{xcolor}
        

# To use this, run quarto render FILENAME --profile standalone